name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Check out the target repository
        uses: actions/checkout@v3
        with:
          repository: Testing-Quest/testing-quest.github.io
          token: ${{ secrets.GITHUB_TOKEN }}
          path: gh-pages

      - name: Clear target repository
        run: |
          rm -rf gh-pages/*

      - name: Copy build files
        run: |
          cp -a dist/. gh-pages/

      - name: Commit and push changes
        run: |
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "deploy - $(date '+%Y-%m-%d %H:%M:%S')"
          git push
